export const languages = {
  vi: {
    type: 'vi',
    title: 'Ứng dựng nghe nhạc',
    hello: 'Xin chào,',
    song: 'Bài hát',
    language: 'Ngôn ngữ',
    profile: 'Tài khoản',
    setting: 'Cài đặt',
    logout: 'Đăng xuất',
    add: 'Thêm bài hát',
    deleteSong: 'Xóa bài hát',
    search: 'Tìm kiếm...',
    listSongs: 'Danh sách bài hát',
    name: 'Tên bài hát',
    genre: 'Thể loại',
    action: 'Hành động',
    play: 'Nghe bài hát',
    edit: 'Cập nhật',
    delete: 'Xóa',
    save: 'Lưu lại',
    cancel: 'Hủy',
    upload: 'Tải lên',
    selected: 'bài hát được chọn',
    songDetails: 'Chi tiết bài hát',
    lastUpdate: 'Ngày cập nhật',
    addSong: 'Thêm bài hát mới',
    describeAdd: 'Vui lòng điền tên, thể loại bài hát và chọn file mp3.',
    describeDelete: 'Bạn có chắc chắn muốn xóa các bài hát đã chọn ?',
    describeDeleteDetail: ' sẽ bị xóa. Tiếp tục ?',
  },
  en: {
    type: 'en',
    title: 'Music Manager',
    hello: 'Hi,',
    song: 'The song',
    language: 'Language',
    profile: 'Profile',
    setting: 'Setting',
    logout: 'Log out',
    add: 'Add',
    delete: 'Delete',
    search: 'Search...',
    listSongs: 'List Songs',
    name: 'Name',
    genre: 'Genre',
    action: 'Actions',
    play: 'Play song',
    edit: 'Edit song',
    save: 'Save',
    cancel: 'Cancel',
    upload: 'Upload',
    selected: 'selected',
    songDetails: 'Song Details',
    lastUpdate: 'Last update',
    addSong: 'Add song',
    describeAdd: 'Please enter the song name, genre and choose a file mp3.',
    deleteSong: 'Delete Song',
    describeDelete: 'Do you want to delete these songs ?',
    describeDeleteDetail: ' will be deleted. Continue?',
  },
};
